dist: xenial
install:
- wget "https://github.com/gohugoio/hugo/releases/download/v${HUGO_RELEASE}/hugo_extended_${HUGO_RELEASE}_Linux-64bit.deb"
- sudo dpkg -i hugo*.deb
script:
- hugo version
- hugo
before_deploy:
- openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_rsa
- echo -e "Host ${DEPLOY_HOST}\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: rsync --recursive --quiet --delete ${TRAVIS_BUILD_DIR}/public/ ${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_DIRECTORY}
  on:
    branch: master
env:
  global:
  - PRODUCTION=true
  - HUGO_RELEASE=0.75.1
  - secure: fZ+9B8Ypr5WX18aVPBAUHlUvDE92dDv2XSG3khxG8826wo6sEyWeZpEQLTvgW4M4+C6YmHN2Rm7MtPsRS/GxUdw0CpsG00Duf04hjV8usG7j84gTmRFvgd41jr7JrH4iM6QdQROpKNbkuY3J+u4Mlfjhf417GTH5aTgPqcstRrAq5dr5c/0F124bASRxtKR4O3P98XE/RSKiYAplvKTYyWDzQbp9UB+4naMS6aim99BNWjkxmXekaoLuiZamGppAKh1JeXfvOZ7aj6aWMa4f0/6h6IRASR0vyayGvh4jraQFskSD9YLTtLKN1HmEwWBjeMjc2I5mZUvTVbHihAvUNkYXVMHClNmxBSoZBB1A9rh+4ft/81TTjBFR9SdFhdggrJoiGec8H3N7SY9QkRcBqlhvDscNqhcsgQLsADp8en7cgQfWiXD+ipVLGa0hQVOwxMhC62KFELhCe7C9IqH8u4D3AGmZY+/vofKD6UO0Q7t8K1pq+uEmWCrBmC0O1GCNtUCcY0gpk+I+rTlEzf5N/hwZUNKmK86FL2UulTN0yiW3oT8fHNg5+eOSGe0KkHgSFFK6LFYIg8KCxhnEO5uLmZflgOeAUIaT/rcu+rHuzY9RbqLmj9fnbdOR/gcR9pQt1DgtY1Ekbxh1j4733nWZebtfNNioXrG+utVWrx/a8s4=
  - secure: RXH+gsadAHJYC9UdKO8ponYy3fVgKmwHOxgnDCsQEqZ7xIU4B59b4cbjC2W4XxTryz/E9phRNhd+W1/D8WQdDWgMAxv2pdG0FGINolDdCrO96IcDSqiAOqstFOSS0PpIGbdRgBD6KmT+G8SDOlsAMuSwHP/093+hzlozB74ct6FwsRRZh7mEtBYBMkVeg7GFcnku1EANaLGACpeTJSF4WGs2rMa41fFMNdbXPixIesgEB7kXNYpEF4SVwIV88HGNQB6mdSpDM58yfsKrjIPAQm/Wh8FXDo7FMZsX3TpSYPaud3ZlXDjZQE816QsXBCkbisnc6dBK3hGKTylMoXm01LMGt4AQrxVaf/9L4DqV5OAR6BeFXONzIb3RsXrTHjtXTSVWL8apbXBT+qR0bpq8z0EeekqBsFuQxolo95db+cjgPlCu4Z1A4GwA8V0TPIZWoKgfmfQVGq9wAbJG+TLuZjJO1+1ANFR0eiLeKC2IwCRAPZqDG7LbNWc2lhHPA3tCa52ynAaVNHAmkpXB085a+gQbKHosYzpYYZJ5o5mfOnJOKl8C/Xe5NaVjpVSL+fGRY5gJWP/HzUu+pF10jGnVH2f4Nv4/uScOKD5hzdWBOABLgtscwH0F5eFbMt+ksvvMCkhzimwthPLQHU3sN9tYoiQfRNssDsH6q6t0hhGB3KU=
  - secure: DunPdU1WtSY3TSw00P42fFE0+uP8YzDKPz2SPUKvBXWVyoxrf00eW8tJE/DCKwxTybF2KVw+CCTilmRUVnWhQRL9s+cra6Jr2aorg+WNUG8c+W0oC2CFDWtuFWNsHbIXDjCh3Sqv368XdiCCLjLevHdi1N7xPQYhqYjyfwP/s0DeOXpEE97vEK7yJ0kCQiTjD5Aje77QPfBwAN7PnjN3ZiJdxmQaf3ayHlDqKAHjZ3cO2jN6lzyqGkrPUym+5fbNj/PhkhG3NYrch1LkZorNtucA3/GfjwJzd79Cu9ENbLmF6ls0ZDPo5eG/UDWJ2MkJcNRqVHiZwTJ67Pqgc/0qJUL11RfvPPzAPTcCtKPCMqImhSX9MMbzZ/laUn7TddOk8lCCG0VlvoDt1Ib8RlSvQcOMqTs1hrRZH1yC2G7kU7+GypbO1K6KtoVBr8M+K6LEpLbddz/YAujy/VEJEWTFC0y47Eyzoc+gTGmefZUmlQifplxyGJuh+fKM7GX+5O72VayE4R5cthNPZ6EC/x7Ss3wy4Ox/u8d1lU+fD61gbPnpBYa+rBppHTzxXKa3vm07LPsFaV0Kx14kKiaFIVpCBt9zyg0lFHg3nXmvM4jibF/vPUqjjDQCJhdpzjP4juuoS2JFtpFxfItdsslzY3FhmsIz+C7WN7iEWwFAw++R9h8=
